name: slack-emoji
version: '2.1'
maintainer: Dan Fithian
license: AllRightsReserved

default-extensions:
  - DataKinds
  - DeriveDataTypeable
  - DeriveGeneric
  - EmptyDataDecls
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - OverloadedStrings
  - PackageImports
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeFamilies
  - ViewPatterns

ghc-options:
  - -Wall
  - -Werror
  - -fwarn-tabs
  - -threaded
  - -O2
  - -rtsopts
  - -with-rtsopts=-N
  - -with-rtsopts=-T

dependencies:
  - aeson
  - base
  - blaze-html
  - classy-prelude
  - conduit
  - conduit-combinators
  - conduit-extra
  - containers
  - csv-conduit
  - fast-logger
  - http-types
  - lens
  - monad-control
  - monad-logger
  - mtl
  - network-uri
  - persistent
  - persistent-sqlite
  - persistent-template
  - random-extras
  - random-fu
  - scalpel
  - text
  - time
  - wai-extra
  - wai-logger
  - warp
  - wreq
  - yesod
  - yesod-core

library:
  source-dirs: "./."

executables:
  slack-emoji:
    main: main.hs
    source-dirs: app
    dependencies:
      - slack-emoji
  scraper-emoji:
    main: main.hs
    source-dirs: scraper
    dependencies:
      - slack-emoji
