host:           "_env:HOST:*4" # any IPv4 host
port:           "_env:PORT:3000"
approot:        "_env:APPROOT:http://localhost:3000"

database:
  user:        "emoji"
  password:    "emoji"
  host:        "_env:MONGO_PORT_27017_TCP_ADDR:localhost"
  port:        "_env:MONGO_PORT_27017_TCP_PORT:27017"
  database:    "emoji"
  connections: 10
